language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test --cov=bioc/
# coverage
after_success:
  - coveralls

notifications:
  email:
    on_success: never # default: change
    on_failure: always
