name: Validate BioC
on: [push]
jobs:
  test:
    name: Test BioC package
    runs-on: ubuntu-latest
    steps:
      - name: Chgeckout repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt install libxml2-utils
          pip install jsonschema

      - name: Validate BioC
        run: |
          xmllint --noout --dtdvalid schema/bioc_v1.dtd tests/bioc/everything.xml
          xmllint --noout --dtdvalid schema/bioc_v2.dtd tests/bioc/everything_v2.xml
          xmllint --noout --schema schema/bioc_v1.xsd tests/bioc/everything.xml
          xmllint --noout --schema schema/bioc_v2.xsd tests/bioc/everything_v2.xml
          jsonschema --instance .\tests\bioc\everything.json .\schema\bioc_schema.json
